{% set name = "adam-robotics" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/ADAM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a9ba46ba57e3a205d74c882ab0fc3197bd24f3b8a4c26ef10828ec1692f3ca81
  patches:
    - 01-allow_long_paths.patch

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python  {{ python_min }}
        - pip
        - wheel
        - setuptools
      run:
        - python  >={{ python_min }}
        - numpy
        - scipy
        - prettytable
        - urdfdom-py
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*pytorch* --ignore-glob=*CasADi*  --ignore-glob=*idyntree*
      requires:
        - python  {{ python_min }}
        - pip
        - pytest
        - icub-models
        - idyntree
        - git
        - gitpython
        - requests

  - name: {{ name|lower }}-casadi
    build:
      noarch: python
    requirements:
      host:
        - python  {{ python_min }}
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - casadi
        - python  >={{ python_min }}
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*pytorch*
      requires:
        - python  {{ python_min }}
        - pip
        - pytest
        - icub-models
        - idyntree
        - git
        - gitpython
        - casadi
        - requests

  - name: {{ name|lower }}-jax
    build:
      noarch: python
    requirements:
      host:
        - python  {{ python_min }}
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - jax
        - python  >={{ python_min }}
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*pytorch* --ignore-glob=*CasADi* --ignore-glob=*idyntree*
      requires:
        - python  {{ python_min }}
        - pip
        - pytest
        - icub-models
        - idyntree
        - git
        - gitpython
        - jax >0.3.0
        - requests

  - name: {{ name|lower }}-pytorch
    build:
      noarch: python
    requirements:
      host:
        - python  {{ python_min }}
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - jax2torch
        - pytorch
        - python  >={{ python_min }}
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*CasADi* --ignore-glob=*idyntree*
      requires:
        - python  {{ python_min }}
        - pip
        - pytest
        - icub-models
        - idyntree
        - git
        - gitpython
        - pytorch
        - jax  >0.3.0
        - requests

  - name: {{ name|lower }}-all
    build:
      noarch: python
    requirements:
      host:
        - python  {{ python_min }}
      run:
        - {{ pin_subpackage('adam-robotics-casadi', max_pin='x.x.x') }}
        - {{ pin_subpackage('adam-robotics-jax', max_pin='x.x.x') }}
        - {{ pin_subpackage('adam-robotics-pytorch', max_pin='x.x.x') }}
        - python  >={{ python_min }}
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity"
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax*
      requires:
        - python  {{ python_min }}
        - pip
        - pytest
        - icub-models
        - idyntree
        - git
        - gitpython
        - casadi
        - pytorch
        - jax  >0.3.0
        - requests

about:
  home: https://github.com/ami-iit/ADAM
  summary: ADAM implements a collection of algorithms for calculating rigid-body dynamics in Jax, CasADi, PyTorch, and NumPy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
    - xela-95
