{% set name = "adam-robotics" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/ADAM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 01c191a0451381679a26777d8dd92116d4c980b094aa6c85972fd9f2aedeed09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - casadi
    - prettytable
    - urdfdom-py
    - jax2torch

test:
  source_files:
    - tests
  imports:
    - adam
  commands:
    # Workaround for glibc <= 2.25 problems,
    # See https://github.com/ami-iit/ADAM/pull/38#issuecomment-1546909762
    - pytest ./tests/ -v -k "not gravity"  # [not win]
    - pytest ./tests/ -v --ignore-glob=*Jax* --ignore-glob=*pytorch*  # [win]
  requires:
    - pip
    - pytest
    - icub-models
    - gym-ignition-models
    - pytorch  # [not win]
    - jax  # [not win]
    - idyntree
    - git
    - gitpython

about:
  home: https://github.com/ami-iit/ADAM
  summary: ADAM implements a collection of algorithms for calculating rigid-body dynamics in Jax, CasADi, PyTorch, and NumPy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
