{% set name = "adam-robotics" %}
{% set version = "0.3.0" %}
{% set minimum_python_version = ">=3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/ADAM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5cd1917be601e9c6b5e619ce8326da6dcbf858bb72c430e9f16377e5a48b225

build:
  number: 2

requirements:
  host:
    - python {{ minimum_python_version }}
  run:
    - python {{ minimum_python_version }}

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - python
      host:
        - python {{ minimum_python_version }}
        - pip
        - wheel
        - setuptools
      run:
        - python {{ minimum_python_version }}
        - numpy
        - scipy
        - prettytable
        - urdfdom-py
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*pytorch* --ignore-glob=*CasADi*
      requires:
        - pip
        - pytest
        - icub-models
        - gym-ignition-models
        - idyntree
        - git
        - gitpython

  - name: {{ name|lower }}-casadi
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - casadi
        - python
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*pytorch*
      requires:
        - pip
        - pytest
        - icub-models
        - gym-ignition-models
        - idyntree
        - git
        - gitpython
        - casadi

  - name: {{ name|lower }}-jax
    build:
      skip: True  # [win]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - jax
        - python
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*pytorch* --ignore-glob=*CasADi*
      requires:
        - pip
        - pytest
        - icub-models
        - gym-ignition-models
        - idyntree
        - git
        - gitpython
        - jax

  - name: {{ name|lower }}-pytorch
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('adam-robotics', max_pin='x.x.x') }}
        - jax2torch
        - pytorch
        - python
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax* --ignore-glob=*CasADi*
      requires:
        - pip
        - pytest
        - icub-models
        - gym-ignition-models
        - idyntree
        - git
        - gitpython
        - pytorch

  - name: {{ name|lower }}-all
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('adam-robotics-casadi', max_pin='x.x.x') }}
        - {{ pin_subpackage('adam-robotics-jax', max_pin='x.x.x') }}  # [not win]
        - {{ pin_subpackage('adam-robotics-pytorch', max_pin='x.x.x') }}
        - python
    test:
      source_files:
        - tests
      commands:
        - pytest ./tests/ -v -k "not gravity"  # [not win]
        - pytest ./tests/ -v -k "not gravity" --ignore-glob=*Jax*
      requires:
        - pip
        - pytest
        - icub-models
        - gym-ignition-models
        - idyntree
        - git
        - gitpython
        - casadi
        - pytorch
        - jax  # [not win]

about:
  home: https://github.com/ami-iit/ADAM
  summary: ADAM implements a collection of algorithms for calculating rigid-body dynamics in Jax, CasADi, PyTorch, and NumPy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
    - xela-95
