{% set name = "adam-robotics" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/ADAM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a157cfffe2261a35408aa9ef66ad74bb26cbfa2d24fe4613a11cc4f7964f0e87
  # Patch merged upstrea in https://github.com/ami-iit/ADAM/pull/40,
  # will be removed at the next release
  patches:
    - 40.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - casadi
    - prettytable
    - urdfdom-py

test:
  source_files:
    - tests
  imports:
    - adam
  commands:
    # Workaround for glibc <= 2.25 problems,
    # See https://github.com/ami-iit/ADAM/pull/38#issuecomment-1546909762
    - pytest ./tests/ -v -k "not gravity"  # [not win]
    - pytest ./tests/ -v --ignore-glob=*Jax* --ignore-glob=*pytorch*  # [win]
  requires:
    - pip
    - pytest
    - gym-ignition-models
    - pytorch  # [not win]
    - jax  # [not win]
    - idyntree

about:
  home: https://github.com/ami-iit/ADAM
  summary: ADAM implements a collection of algorithms for calculating rigid-body dynamics in Jax, CasADi, PyTorch, and NumPy.
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
